kind: ServiceAccount
apiVersion: v1
metadata:
  name: edgelessdb
  namespace: {{ .Release.namespace }}
  labels:
    app.kubernetes.io/name: EdgelessDB
    app.kubernetes.io/component: ServiceAccount
    app.kubernetes.io/part-of: EdgelessDB
    app.kubernetes.io/version: {{ .Values.global.image.version }}
    app.kubernetes.io/created-by: {{ .Values.global.createdBy }}
{{- if .Values.global.pullSecret }}
imagePullSecrets:
  - name: {{ .Values.global.pullSecret }}
{{- end }}